<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIlzcFw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIlzcFw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIlzcFw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIlzcFw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOIlzcFw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OIlzcFw',
    'container.build_id' => '07adb4cc',
    'container.build_time' => 1648826098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIlzcFw');
