package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;



/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme1;
 
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme1 = UIManager.initFirstTheme("/theme1");
 
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
             if(current != null){
            current.show();
            return;
        } 
        int id;
           //  new Ticketf (theme).show();
           //new ListE(theme1,0,current).show();
           //   new Ajoutticket (theme).show();
      //  new ListEventForm (current,0,theme).show();
      // new AfficheEForm(theme,"").show();
    //new WalkthruForm(theme).show();
   //new SignInForm(theme1).show();
 
  // new AjoutCategorie(theme).show();
    // new AjoutSalle(theme).show();
 // new SplashForm(theme1).show();
  new SignInForm_1().show();
  //    new ListSalle(theme).show();
    //new ListCategorie(theme).show();
  //  new ListProduct(theme1,current).show();
  // new ListCategory(theme, current).show();
     // new AjoutLigneForm(theme).show();
    // new AjoutCommandeForm(theme).show();
    }
    

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
