<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eventl extends \App\Entity\Eventl implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'idevent', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'datefin', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'datedebut', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'ticket', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'Participation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'idevent', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'datefin', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'datedebut', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'ticket', '' . "\0" . 'App\\Entity\\Eventl' . "\0" . 'Participation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eventl $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(\DateTimeInterface $datefin): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$datefin]);

        return parent::setDateFin($datefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdevent(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdevent();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdevent', []);

        return parent::getIdevent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdevent(string $idevent): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdevent', [$idevent]);

        return parent::setIdevent($idevent);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure(string $heure): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebut', []);

        return parent::getDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebut(\DateTimeInterface $datedebut): \App\Entity\Eventl
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebut', [$datedebut]);

        return parent::setDatedebut($datedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTicket(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicket', []);

        return parent::getTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function __construct1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__construct1', []);

        return parent::__construct1();
    }

}
